import Layout from '@/components/Layout'
import Head from 'next/head'
import React from 'react'

function About() {
  return (
    <>
    <Head>
        <title>Nyrell Leonor - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Layout>
        About
    </Layout>
    </>
  )
}

export default About