import Head from "next/head";
import Typed from "typed.js";
import Link from "next/link";
import { useRef, useEffect } from "react";
import { Parallax, ParallaxLayer, IParallax } from "@react-spring/parallax";
import { animated, useSpring } from "@react-spring/web";
import Nav from "@/components/Nav";
import Hero from "@/components/Hero";

export default function Home() {
  const typedRef = useRef<HTMLParagraphElement>(null);
  const parallaxRef = useRef<IParallax>(null);

  useEffect(() => {
    const typedOptions = {
      strings: ["Front End Developer", "Creative", "Designer"],
      typeSpeed: 70,
      loop: true,
      backSpeed: 70,
      showCursor: false,
    };

    if (typedRef.current) {
      const typed = new Typed(typedRef.current, typedOptions);
      return () => {
        typed.destroy();
      };
    }
  }, []);

  return (
    <>
      <Head>
        <title>Nyrell Leonor - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <section className="intro-section">
          <Parallax ref={parallaxRef} pages={2}>
            <ParallaxLayer
              offset={0}
              speed={1}
              style={{ backgroundColor: "hsl(28, 62%, 76%)", height: "100%" }}
            ></ParallaxLayer>
            <ParallaxLayer offset={0} speed={1.5}>
              <Nav />
              <Hero button={<button type="button" className="page-btn" onClick={() => parallaxRef.current?.scrollTo(1)}>Click me</button>}/>
              
            </ParallaxLayer>

            <ParallaxLayer
              offset={1}
              speed={1}
              style={{ backgroundColor: "blue" }}
            ></ParallaxLayer>
            <ParallaxLayer offset={1.1} speed={1.3}>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam
              maxime quae aut fugit saepe! Similique unde rerum, consectetur,
              distinctio numquam, reiciendis omnis perspiciatis harum quod
              obcaecati aspernatur nisi optio consequatur.
            </ParallaxLayer>
          </Parallax>
        </section>
      </main>
    </>
  );
}
