import Head from "next/head";
import { useRef } from "react";
import { Parallax, ParallaxLayer, IParallax } from "@react-spring/parallax";
import Nav from "@/components/Nav";
import Hero from "@/components/Hero";
import { CgArrowLongDownC } from "react-icons/cg";
import { TbGhost } from "react-icons/tb";

export default function Home() {
  const parallaxRef = useRef<IParallax>(null);

  return (
    <>
      <Head>
        <title>Nyrell Leonor - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <section className="intro-section">
          <Parallax ref={parallaxRef} pages={2}>
            <ParallaxLayer
              offset={0}
              speed={1}
              style={{ backgroundColor: "hsl(28, 62%, 76%)", height: "100%" }}
            ></ParallaxLayer>
            <ParallaxLayer offset={1.3} speed={-0.3}>
              <article className="ghost-blurb">
              <TbGhost
                style={{
                  display: "inline-block",
                  width: "8em",
                  height: "8em",
                  marginLeft: "70%",
                  position: 'relative'
                }}
                />
                <span>Enjoy!</span>
              </article>
            </ParallaxLayer>
            <ParallaxLayer offset={0} speed={1.5}>
              <Hero
                button={
                  <button
                    type="button"
                    className="page-btn"
                    onClick={() => parallaxRef.current?.scrollTo(1)}
                  >
                    <CgArrowLongDownC />
                  </button>
                }
              />
            </ParallaxLayer>

            <ParallaxLayer
              offset={1}
              speed={1}
              style={{ backgroundColor: "blue" }}
            ></ParallaxLayer>
            <ParallaxLayer offset={1.1} speed={1.3}>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam
              maxime quae aut fugit saepe! Similique unde rerum, consectetur,
              distinctio numquam, reiciendis omnis perspiciatis harum quod
              obcaecati aspernatur nisi optio consequatur.
            </ParallaxLayer>
          </Parallax>
        </section>
      </main>
    </>
  );
}
